# Problem 3.1

**Consider the following biological sequence analysis tasks. For each task, (A) write the type of sequence analysis algorithm that would best accomplish the task, and (B)explain why. The algorithms have been discussed in class in Lectures 3-5. There may be more than one correct choice per task (you need only provide one).**

**1.Visualize a sequence inversion that occurred between two closely related viral strains.**

I think the best algorithm to visualize them is Dot-Matrix algorithm. First of all, Dot-Matrix algorithm can be used to visualize similarities and differences between two sequences according to the diagnal. When we want to visualize the sequence inversion between to related viral strains, we can observe whether the Dot-Matrix has diagonal patterns going in the opposite direction. It's clear and easy for observe in Dot-Matrix(There are two diagonals that are vertical to each other).

**2.Given highly conserved ribosomal RNA sequences from five insect species, 
determine quantitatively which two species are the most closely related.**

I suppose that most appropriate algorithm to solve this problem that we learned in Lec3-5 is the Longest Common Subsequence(LCS). Because the five insect species have highly conserved regions, thus we can use LCS to finds the longest subsequence that is common to all sequences. By the LCS, we can quantify the similarity among the species by the length of conserved region, further to determine which two species are the most closely related.

**3.Evaluate a new sequencing technology by comparing the results of a 300 BP 
read to a previous result based on Sanger sequencing. The beginning of the 
Sanger sequence is known to contain some “junk”—do not penalize for this.**

We can choose Needleman-Wunsch algorithm to perform sequence alignment which can help to find the difference. Needleman-Wunsch algorithm is a global alignment algorithm, it can handle with the alignment with different length sequences. And through the optimal global alignment, we can detect the changes between new and old sequences, which is called 'junk'.

**4.Identify a shared DNA binding domain in two otherwise unrelated proteins.**

I think the local alignment algorithm like Smith-Waterman are appropriate for this quesiton. Local alignment algorithms are useful to find those regions with high similarity, which indicated sahred domians or motifs in those protein sequences. Those regions may indicate conserved regions in protein, which share the same function between those proteins.

# Problem 3.2

**(A) Manually fill out a dynamic programming (DP) matrix for the pair of short DNA 
sequences below using the Needleman-Wunsch global alignment algorithm, and the 
scoring scheme below  
(B) Include traceback arrows  
(C) Report the score of the optimal alignment(s)  
(D) Write out one possible optimal alignment  
(E) How many equally optimal alignments are there (i.e., are there any ties)?**

The score of the optimal alignment is: 6  
One possible optimal alignment for these two sequence is 'GATGGCT' with 'CA_GG_T'  
There is no equally optimal alignment in this problem

![scoring scheme](result.jpg)

# Problem 3.3

**Write a python script called dotcounter.py that, given a pair of strings A and B, determines the total number of dots that would appear in the dot plot comparing the two strings and prints their coordinates. Your program does not need to draw the actual dot plot!**


In [2]:
def dotcounter(seq1,seq2):
    #set a variable to count dot
    match=0
    #read through each character in seq1
    for i in range(0,len(seq1)):
        #read through each character in seq2
        for j in range(0,len(seq2)):
            #If statement to judge whether there is a match
            if seq1[i]==seq2[j]:
                match+=1
                #print the pair of matches
                print('A'+str(i+1),'and',"B"+str(j+1))
            #Print the dots that are matched
    return(print('Total matches:\n'+str(match)))



In [3]:
dotcounter(seq1='ACTTGGCCAT',seq2='AGTAGCGCCT')

A1 and B1
A1 and B4
A2 and B6
A2 and B8
A2 and B9
A3 and B3
A3 and B10
A4 and B3
A4 and B10
A5 and B2
A5 and B5
A5 and B7
A6 and B2
A6 and B5
A6 and B7
A7 and B6
A7 and B8
A7 and B9
A8 and B6
A8 and B8
A8 and B9
A9 and B1
A9 and B4
A10 and B3
A10 and B10
Total matches:
25


**Thought question (full points for explaining your logic, right or wrong): How many dots would you expect to observe given two random DNA sequences of length ten? Do you think that the two sequences from (B) are random or related?**

I suppose that for two random DNA sequences of length ten, the dot that expected to be observed is 25. The reason is, at each position, the probability is 0.25 for A,C,T,G. Thus for each position at the first sequence, the expected match at another sequence is 0.25*10=2.5. The first sueqnce has 10 position, I expect to observe 2.5*10=25 dots. Because the expect observed dots for a random sequence with length ten is 25, I think the two sequences are random.

# Problem 3.4

In [1]:
import numpy as np
import time 
#Define a function which contains 5 parameters, two sequence and the scoring shceme, here the scoring scheme has the default value.
def global_alignment(seq1,seq2,match=1,mismatch=0,gap=-1):
    #Set up a matrix to contain the scoring result, the dimension is len(seq2)*len(seq1)
    matrix=np.zeros((len(seq2)+1,len(seq1)+1))
    
    #initial lize the matrix,look through each position score in row 0 and col 0
    for  i in range(1,len(seq1)+1):
        matrix[0,i]=matrix[0,i-1]+gap
    for  j in range(1,len(seq2)+1):
        matrix[j,0]=matrix[j-1,0]+gap

    #Set up a dictionary to contain the traceback information.
    dic={}
    #read through each cell from row 1 and col 1
    for x in range(1,len(seq1)+1):
        for y in range (1,len(seq2)+1):
            #varify whether these two characters is match or not
            if seq1[x-1]==seq2[y-1]:
                status=match
            else:
                status=mismatch
            #Use the definition to decide the score of each position
            values=[matrix[y-1,x-1]+status,matrix[y-1,x]+gap,matrix[y,x-1]+gap]
            #Each position should contain the max value according to those fomulars
            matrix[y,x]=max(values)
            #The pointer store the traceback information, which value is selected by max funtion.
            pointer=values.index(matrix[y,x])
            
            #With the different value that selected from the definition, store the information to dictionary with the key equal to the position.
            if pointer == 0 and status==match:
                dic[str(y)+"_"+str(x)]='match'
            elif pointer == 0 and status==mismatch:
                dic[str(y)+"_"+str(x)]='mismatch'
            elif pointer == 1:
                dic[str(y)+"_"+str(x)]='seq1_gap'
            elif pointer == 2:
                dic[str(y)+"_"+str(x)]='seq2_gap'
    
    #Create new variable store the optimal alignment.
    align_seq1=''
    align_seq2=''
    
    #Store the length of those two sequence
    q=len(seq1)
    p=len(seq2)
    
    #From the last position of the scoring dataframe, traceback the process and generate the optimal global alignment
    while p>=1 and q>=1:
        #From dictionary we can know the score is added by math,mismatch or gap, thus we can assemble the new sequence.
        #If the value in dictionary is match or mismatch, both characters added to the new sequence, and the row number-1,col number -1.
        if dic[str(p)+"_"+str(q)]=='match'or dic[str(p)+"_"+str(q)]=='mismatch':
            align_seq1=seq1[q-1]+align_seq1
            align_seq2=seq2[p-1]+align_seq2
            q-=1
            p-=1
        #If the value in dictionary is seq1_gap, it means the sequence 1 need a '_' in the optimal global alignment,thus row -1.
        elif dic[str(p)+"_"+str(q)]=='seq1_gap':
            align_seq1='_'+align_seq1
            align_seq2=seq2[p-1]+align_seq2
            p-=1
        #If the value in dictionary is seq2_gap, it means the sequence 2 need a '_' in the optimal global alignment, thus col -1.
        elif dic[str(p)+"_"+str(q)]=='seq2_gap':
            align_seq1=seq1[q-1]+align_seq1
            align_seq2='_'+align_seq2
            q-=1
    
    return(print('the scoring matrix is:\n',matrix,'\n',"The optimal global alignment is:\n",align_seq1,'\n',align_seq2))

In [2]:
global_alignment(seq1='GATTACA',seq2='GATAGA',match=2,mismatch=0,gap=-3)

the scoring matrix is:
 [[  0.  -3.  -6.  -9. -12. -15. -18. -21.]
 [ -3.   2.  -1.  -4.  -7. -10. -13. -16.]
 [ -6.  -1.   4.   1.  -2.  -5.  -8. -11.]
 [ -9.  -4.   1.   6.   3.   0.  -3.  -6.]
 [-12.  -7.  -2.   3.   6.   5.   2.  -1.]
 [-15. -10.  -5.   0.   3.   6.   5.   2.]
 [-18. -13.  -8.  -3.   0.   5.   6.   7.]] 
 The optimal global alignment is:
 GATTACA 
 GA_TAGA
